//
// Created by Rubén Osorio López on 2/12/16.
//

#ifndef TRAVELLERPROBLEM_BETTERTABUSEARCH_SOLUTIONHELPER_H
#define TRAVELLERPROBLEM_BETTERTABUSEARCH_SOLUTIONHELPER_H

#include "Solution.h"

int *getGreedyData();

#endif //TRAVELLERPROBLEM_BETTERTABUSEARCH_SOLUTIONHELPER_H
